services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
  db:
    image: postgres
    container_name: postgres_wisblog
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: local-password

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
volumes:
  db-store:
